filegroup(
    name = "dashboards",
    srcs = glob(["dashboards/**"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "provisioning",
    srcs = glob(["provisioning/**"]),
    visibility = ["//visibility:public"],
)
