server {
    listen 443 ssl;
    server_name local.wolfe.dev localhost;

    error_log /dev/stderr warn;

    ssl_certificate /etc/nginx/certs/local.wolfe.dev.crt;
    ssl_certificate_key /etc/nginx/certs/local.wolfe.dev.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location = /status {
        access_log off;
        proxy_pass http://auth_service:8080/status;
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://auth_service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
